server:
  port: 8080

spring:
  application:
    name: api-gateway
cloud:
  gateway:
    routes:
      - id: producto-service
        uri: http://localhost:8084
        predicates:
          - Path=/producto/**

      - id: taxonomia-service
        uri: http://localhost:8082
        predicates:
          - Path=/taxonomia/**

      - id: js-service
        uri: http://localhost:8083
        predicates:
          - Path=/test
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: INFO