server:
  port: 8079

spring:
  main:
    web-application-type: servlet
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: producto-service
          uri: http://localhost:8084
          predicates:
            - Path=/producto/**
        - id: taxonomia-service
          uri: http://localhost:8081
          predicates:
            - Path=/taxonomia/**
        - id: js-service
          uri: http://localhost:8083
          predicates:
            - Path=/test/**
        - id: user-security
          uri: http://localhost:8085
          predicates:
            - Path=/auth/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: INFO

jwt:
  secret: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
  expiration: 3600000