server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/producto_microservicio?createDatabaseIfNotExist=true
    username: root
    password: qwertyuiop
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true